"""
Candidate Loader

Loads candidate research gaps generated by Phase 5
(Graph Motif Analysis + GraphSAGE Link Prediction).

Output:
    List[CandidateEdge]
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from typing import List


# ---------------------------------------------------------------------
# Candidate Edge Schema
# ---------------------------------------------------------------------

@dataclass
class CandidateEdge:
    gap_id: str
    source_node: str
    target_node: str
    relation: str
    shared_entity: str
    motif_score: float
    graphsage_score: float
    confidence: float
    status: str


# ---------------------------------------------------------------------
# Candidate Loader
# ---------------------------------------------------------------------

class CandidateLoader:
    """
    Loads candidate gap edges produced in Phase 5.
    """

    def __init__(self, json_path: str | Path):
        self.json_path = Path(json_path)

    def load(self) -> List[CandidateEdge]:
        """
        Load all candidate edges.

        Returns:
            List[CandidateEdge]
        """

        if not self.json_path.exists():
            raise FileNotFoundError(
                f"Candidate file not found: {self.json_path}"
            )

        with open(self.json_path, "r", encoding="utf-8") as f:
            data = json.load(f)

        candidates = []

        for item in data:

            candidate = CandidateEdge(
                gap_id=item.get("gap_id", ""),
                source_node=item.get("source_node", ""),
                target_node=item.get("target_node", ""),
                relation=item.get("relation", ""),
                shared_entity=item.get("shared_entity", ""),
                motif_score=float(item.get("motif_score", 0.0)),
                graphsage_score=float(item.get("graphsage_score", 0.0)),
                confidence=float(item.get("confidence", 0.0)),
                status=item.get("status", "")
            )

            candidates.append(candidate)

        return candidates


# ---------------------------------------------------------------------
# Example Usage
# ---------------------------------------------------------------------

if __name__ == "__main__":

    loader = CandidateLoader(
        "data/processed/final_gap_candidates.json"
    )

    candidates = loader.load()

    print(f"Loaded {len(candidates)} candidate edges.\n")

    if candidates:
        print(candidates[0])